"""empty message

Revision ID: a669aeb2303c
Revises: 8be65a292f9e
Create Date: 2025-04-16 11:04:47.269320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a669aeb2303c'
down_revision: Union[str, None] = '8be65a292f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('detection_set_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_detections_detection_set_id'), 'detections', ['detection_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_detection_set_id'), table_name='detections')
    op.drop_column('detections', 'detection_set_id')
    # ### end Alembic commands ###
